version: '3.7'

services:
  example1:
    container_name: "example"
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python example.py"
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"

  example2:
    container_name: "example1"
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python example.py"
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"